### ISSUE TITLE
update frozen

### ISSUE THREAD

**Issue by eoli3n** [ArturSierzant/OMPD#1]
Hi,
Update db failed, then i can't stop it, or relaunch.
I restarted nginx, php-fpm, mariadb, mpd, nothing works, it keep saying "update in progress".
Is there a lock file ?
What could i do to force restart update.
Have a nice day.

**Comment by eoli3n** [comment]
I updated to 1.0.2, and then drop ompd database, to do a fresh start...
When i first open ompd, i see "database created, connect with admin admin", then i update, it starts well, 15 albums comes in Library, then it seems blocked and nothing more happens.

**Comment by ArturSierzant** [comment]
I guess update procedure stops because it meets files, which it can't handle. It can be a problem with tags or corrupted files or bug in update procedure. You can try to find files causing problem by using debug option in config file: edit /include/config.inc.php: find $cfg['debug'] and change its value to true.
Since your last update failed you probably have to reset update status: go to config page in www, scroll to 'update'; in 'comment' column you should see something like 'update in progress...' Click 3rd dot and cancel sign should appear - click it and update status should be reset allowing to start new update. Alternatively you can remove all records from table update_progress in database.
Next start update - update progress will be logged in /tmp/update_log.txt in ompd dir (make sure that user your www server runs as has write access to this directory)

When update hangs, check update_log.txt - you should be able to find out on which file and on which stage process stopped. Check this file or temporary remove this album from media dir and run update again (use method described above to reset update status).

**Comment by eoli3n** [comment]
i did everything you said + 
- i mp3val repair every mp3 files, it repairs lots of errors, now mp3val says everything ok
- i removed every embed art in mp3 files, with beets embedart plugin

Log file dont says anything more,
I moved music/A* ./ then update works.
Then restore one per one A* in music dir, then i found the problem was a corrupt png in one of these albums...
Thx for helping

**Comment by ArturSierzant** [comment]
I'm glad you figured it out. Do you still have this corrupted file? Could you share it so I could correct code to handle such cases? Apparently there is something wrong with the update procedure, although this procedure should already handle corrupted images (they are ignored and, at the end of update process, link to the list of corrupted images is displayed).

**Comment by eoli3n** [comment]
ah no, sorry i removed it. I i will check on my backup, but it's at home, where i'm not until Saturday.
It happens when i removed all my cover with zmv with zsh
zmv '(*)/(*)/(*).jpg' '$1/$2/folder.jpg'
zmv '(*)/(*)/(*).png' '$1/$2/folder.png'

Normally, zmv warns about conflicts, if there are two files which match in a folder... maybe there was an error with this procedure. I didnt try to open corrupted jpgs, before remove them.

**Comment by eoli3n** [comment]
here's a corrupted file 
http://sprunge.us/WQcZ

**Comment by ArturSierzant** [comment]
Thank you for the file. Unfortunately I can't reproduce this problem on my systems (Win7, Win10, two linux-based, one Android, running Apache/lighttpd, PHP7/5.5/5.4, mysql/mariadb). In all cases update procedure works as it should: corrupted file is ignored and update process ends in normal way.
When I find some time, I'll try to use setup like yours and repeat tests.
Thank you for feedback.
Regards.

**Comment by othmar52** [comment]
after running importer for approximately 8 hours i also have a frozen update without much info why it happened

the O!MPD debug log stops with
```
fileStructure TrackUpdate: /path/to/MATUTO____THE_DEVIL_AND_THE_DIAMOND___(USA2013)___(280k_VBR)/11_Thousand_to_Three.mp3
fileStructure TrackUpdate: /path/to/MATUTO____THE_DEVIL_AND_THE_DIAMOND___(USA2013)___(280k_VBR)/12_Matuto_Chant.mp3
fileStructure ImageUpdate: /path/to/MATUTO____THE_DEVIL_AND_THE_DIAMOND___(USA2013)___(280k_VBR)/01_Toca_Do_Sino.mp3
fileStructure ImageUpdate d: false
```
the php error log only shows notices but no fatal error

```
PHP Warning:  fread(): Length parameter must be greater than 0 in /path/to/ompd/getid3/getid3/getid3.php on line 1702
```

i will try another O!MPD/MPD instance having only that album soon. hopefully i can reproduce this error...

**Comment by ArturSierzant** [comment]
othmar52, any luck with update? It seems that there is a problem with cover image for `MATUTO____THE_DEVIL_AND_THE_DIAMOND___(USA2013)___(280k_VBR)` and this problem is not properly handled by function....

**Comment by othmar52** [comment]
>i will try another O!MPD/MPD instance having only that album soon. hopefully i can reproduce this error...

i can **not** reproduce this error when having only this single album in my mpd database
