### ISSUE TITLE
Youtube-dl dont work

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#108]
Hello Artur,

when I install youtube-dl 

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

and

$cfg['python_path'] = '/usr/bin/python3.5';
$cfg['youtube-dl_path'] = '/usr/local/bin/youtube-dl';

youtube-dl doesn't work.

can you help me

thanks 

cliff

**Comment by ArturSierzant** [comment]
I've noticed that it also is not working in my system. It turned out that YT changed the audio format name from `140 - audio only (DASH audio)` to `140 - audio only (tiny)` - it has to be changed in `config.inc.php` - `$cfg['youtube_audio_format_name']` 
Besides I had to change the way of searching that name in data received from YT. It is done in 9a3b857, so please try to update and check if that helped also in your case.

**Comment by marcbth** [comment]
Hello Artur,
thats work for me.

Perfect.

Many thanks.

Cliff
