### ISSUE TITLE
Tidal search error

### ISSUE THREAD

**Issue by paradix** [ArturSierzant/OMPD#125]
Hi, 
today I noticed following error while looking up TIDAL results

![image](https://user-images.githubusercontent.com/3265277/85058002-c4edef00-b1a1-11ea-84be-a9c4ca16d417.png)

Is there any way to check the exception causing this error?
Does O!MPD has any debug log besides the update debug?

**Comment by ArturSierzant** [comment]
Hi,
does it only happen for albums or generally for all Tidal actions? Does it happen all the time or only from time to time?

There is no additional debugging, unfortunately. But in this case `null` means that you probably received empty answer from Tidal. In case of error Tidal returns something like this:
```
array(3) {
  ["status"]=>
  int(401)
  ["subStatus"]=>
  int(6004)
  ["userMessage"]=>
  string(13) "Invalid token"
}
```
O!MPD takes value of `userMessage` and displays it as `Error message`. Since it's `null` I think that whole answer is null/empty.

Maybe try with other token.

Regards,
Artur

**Comment by paradix** [comment]
This happens all the time in all the use cases, but it used to work with the token I have.
Also this token works with a different application.

**Comment by ArturSierzant** [comment]
To see the whole answer from Tidal try this:
in `tidalapi\tidal_api.php` find line 79 which is:
`$errors['error'] = $res_json["userMessage"];`
and replace it with:
`$errors['error'] = $server_output;`

In my case, for very long token which used to work some time ago, but is not valid anymore, I have the following result:
![image](https://user-images.githubusercontent.com/22481059/85133292-b9023b80-b23a-11ea-8082-e3b4bec0f9dd.png)

Without changes in `tidal_api.php` and with invalid token I have the same result as You:
![image](https://user-images.githubusercontent.com/22481059/85133703-80169680-b23b-11ea-81b5-4e4c497f4462.png)

Anyway, please try it and let's see what is the answer from Tidal.

**Comment by paradix** [comment]
I get the same error message with my token

```
Error message:

{"status":401,"subStatus":3009,"userMessage":null}
```

**Comment by ArturSierzant** [comment]
Try to use uncommented token from here:
https://cdn.jsdelivr.net/gh/yaronzz/Tidal-Media-Downloader@latest/Else/tokens.json

**Comment by paradix** [comment]
found it elsewhere and it works. Dzięki 👍

**Comment by ArturSierzant** [comment]
Proszę :)
