### ISSUE TITLE
1983fab GoogleAPI used for YouTube searches

### ISSUE THREAD

**Issue by marcbth** [ArturSierzant/OMPD#128]
Hi, Artur,

can you take back your commitment?

Why?

why do I have to register with google? give out my data. It has worked before as well. For the user it is an additional hurdle.

What does the integration of hra do? 

I am happy to read from you.

Cliff

**Comment by ArturSierzant** [comment]
Hi Cliff,

I changed this because previous method (asking youtube.com and parsing the answer) stopped to work. Google made some changes in www page layout:
* they started to use tags like `ytd-video-renderer`, which are not supported by PHPsimpleHTMLDomParser
* they changed the way of generating page - now PHPsimpleHTMLDomParser can't get whole page

But don't worry - you don't have to register with Google: 
* you can use API key provided by O!MPD - it's written in `config.inc.php`. This is developer key which has limitation: 10000 credits per day (this gives about 95 searches - not much, I know...)
* you can set `$cfg['youtube_key'] = ""` or just comment this out and O!MPD will use simple query in google.com and parse the answer. It has some disadvantages: gives about 10 results (or less) and may stop working when Google changes layout of www page.

The most reliable way is to use API. It requires to create Google account, but it may be a fake one, used only to get API key. I know it's not the most convenient way - that's why I left possibility to use google.com. 

If you want to get back to previous way (though it stopped working for me...), all you have to do is replace `ajax-yt-search.php` with version from before last two commits (e.g. https://github.com/ArturSierzant/OMPD/blob/4433cdd454c9c3d8c003ac884847d1981ee670f4/ajax-yt-search.php).

And sorry, no good news about HRA so far, I still didn't manage to publish version 1.06...

Regards,
Artur
