### ISSUE TITLE
Support multi-valued genre tags.

### ISSUE THREAD

**Issue by dseomn** [ArturSierzant/OMPD#19]
Hi,

Many of the files in my collection have more than one genre tag, but O!MPD only displays one genre per file. Searching by genre also seems to be limited to one genre per file. Would you mind adding support for multi-valued genre tags? (Also, the genre "added" appears in my list despite not having any files with that genre. Is that related, or is that a separate bug?)

![screenshot from 2016-12-04 16-37-14](https://cloud.githubusercontent.com/assets/15314936/20869431/20c393b4-ba40-11e6-935d-18dba26f375d.png)
![screenshot from 2016-12-04 16-41-41](https://cloud.githubusercontent.com/assets/15314936/20869465/b33527a8-ba40-11e6-8ca0-b1e3a91f6f2a.png)
![screenshot from 2016-12-04 16-44-39](https://cloud.githubusercontent.com/assets/15314936/20869482/03de7db2-ba41-11e6-8559-f39928c2725f.png)

**Comment by dseomn** [comment]
Here are some test files, in case that helps:

[multiple-genre-test-files.zip](https://github.com/ArturSierzant/OMPD/files/629913/multiple-genre-test-files.zip)

**Comment by dseomn** [comment]
It looks like the issue of "added" being in the genre list might be caused by https://github.com/JamesHeinrich/getID3/issues/89.

**Comment by ArturSierzant** [comment]
Hi,
I've just done some testing: to tag my files I use Mp3tag v2.75. When I change genre value of a mp3 file to 'added/2016', Mp3tag shows correct value while getID3 shows only 'added' (and this is also what O!MPD sees) - you're right: that's why you have 'added' in genre list.

As for multi-genre: since you're not the first person who asks about this, I'll add it to TODO list.

Best regards,
Artur

**Comment by ArturSierzant** [comment]
Done in 0f13f27 - but full rescan of media dir is required (or at least full rescan of dirs with multi-genre albums - this can be done from file browser). You can simply delete all from table `track` and update DB.
