### ISSUE TITLE
Fast forward fails

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#46]
I haven't tested other browsers however in Firefox 52.0.2 (64-bit) I'm finding I am unable to click/drag the track timeline, it simply restarts the track from the beginning if I try.

**Comment by ArturSierzant** [comment]
Yes, it happens when you play files outside of mpd database. In this case O!MPD sends to mpd stream and unfortunately clicking track timeline doesn't work properly. There is also no additional info like
`End at: 21:16 • Left: 00:34:52 • Total: 00:59:42`
 next to 'Playlist'. This issue is on TODO list to fix.

**Comment by othmar52** [comment]
@ArturSierzant 
i had the same issue in sliMpd. i found out that for some reason the seek command had been fired twice
causing a restart of the track.

maybe O!MPD seeking bug has the same reason!?

**Comment by ArturSierzant** [comment]
Done in 647fa14 - now length of track for stream is taken from `status` function (previously it was `currentsong`) and `seek` function is used instead of `seekcur`.

**Comment by brendan-pike** [comment]
Fantastic, can't wait to test :)

**Comment by brendan-pike** [comment]
Thanks, its working great

**Comment by brendan-pike** [comment]
I came across an album tonight where the fast forward was failing.  Yes on moode it worked, if you want I can provide a sample track privately for debugging.  Let me know, cheers.

**Comment by ArturSierzant** [comment]
Hi,I'm sorry for late answer, but I've got a lot of work recently...That's interesting - yes, please, send me that file, I'll try to investigate this...Best regards,ArturDnia 1 czerwiec 2017 o 12:42 DB Informatics <notifications@github.com> napisał(a):I came across an album tonight where the fast forward was failing. Yes on moode it worked, if you want I can provide a sample track privately for debugging. Let me know, cheers.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
