### ISSUE TITLE
Can O!MPD sort the tracks by Disc Number?

### ISSUE THREAD

**Issue by Trillien** [ArturSierzant/OMPD#59]
Hello,

I figure out O!MPD doesn't sort tracks per disc:
At the time an album is selected to Play or Add to the playlist, in case of several discs distinguished by the MetaData tag "Disc Number", the tracks are only sorted by their tag Track Number. It results the discs are mixed together into the playlist. All tracks number 01, then all tracks number 02...

Is their a possibility to sort the tracks considering Disc Number and Track Number tags?

Trillien

**Comment by ArturSierzant** [comment]
Hi,
this should work... It was reported in #22 and fixed in f5ebd96, but maybe there is another problem in your case. Please first check if data from tag `discnumber` are properly added to DB: look into table `track` , column `disc`. If this column is equal for all discs in multidisc album, then try to force update data for that album (in album view click `Update album`) and then check again table `track`. 
This should work if you write tag `discnumber` as plain number (e.g. `01` or `1`) or using `/` (e.g. `01/02` - disc 1 from 2). In other case please write, what notation you use.
