### ISSUE TITLE
config.inc.php is not gitignored

### ISSUE THREAD

**Issue by othmar52** [ArturSierzant/OMPD#8]
Hi Artur,
i noticed that `include/config.inc.php` is not really gitignored. maybe the reason is that you have added the path in your gitgnore **after** the file was pushed to git origin.

to really remove it from repo you'll have to do something like
`git rm include/config.inc.php`

But this will bring you another problem:
some of your php files require this specific file without checking if this file exists. pretty sure ompd will show tons of errors in case $cfg or some of its array keys does not exist.

A possible solution for this problem would be:
1. remove the line `include/config.inc.php` from gitignore
2. add a line `include/config.local.php` to your gitignore
3. add something like that to the **end** of your `include/config.inc.php`

``` php
if(file_exists(NJB_HOME_DIR . 'include/config.local.php') === true) {
  require NJB_HOME_DIR . 'include/config.local.php';
}
```

but this solution would also require an update in your documentation/setup instruction :/
maybe you find a better way!?

**Comment by ArturSierzant** [comment]
Thank you for notice this. Actually this file should be in the repo - without it ompd will not work. I probably misunderstood the idea of `.gitignore` file. I put `config.inc.php` there, because I didn't want it to be pushed during commit (my `config.inc.php` has different settings then the one from repo). Then I realised that I can simply omit it during stage.
You're right - I added it to `.gitignore` after initial commit. And now I see why this file is still visible in the list of files to stage. 

Anyway in next commit I'll remove it from `.gitignore`. I hope then it will work as I want...

**Comment by othmar52** [comment]
>Actually this file should be in the repo - without it ompd will not work.

i know! therefore you have to separate "O!MPD shipped default config" (not gitignored) and "individual users config"(gitignored) into **2 different files**! You can't gitignore sections of a file.

To proove that it is a problem currently you can follow those steps:
1. do a fresh git clone of the ompd repo
2. customize your config
3. type `git status` and you will see that your working directory is **not** clean

**Comment by ArturSierzant** [comment]
Now I see the problem (I guess...). I used your solution, but I check if local config exists in `include/initialize.inc.php`, not in `include/config.inc.php`. I hope this will work OK...
